# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
# env = GDK_SCALE,2
env = GDK_SCALE,1
monitor=DP-3,preferred,0x0,1
# monitor=HDMI-A-1,disable
monitor=HDMI-A-1,preferred,1200x1440,1

windowrule = monitor DP-3, class:^(steam_app_.*)$
# windowrulev2 = workspace name:steam, class:^(steam_app_.*)$ 

# windowrule = monitor DP-3, match:class "^(steam_app_.*)$" 



workspace=name:1, monitor:DP-3
workspace=name:2, monitor:DP-3
workspace=name:3, monitor:DP-3
workspace=name:4, monitor:DP-3
workspace=name:5, monitor:DP-3

workspace=name:7, monitor:HDMI-A-1
workspace=name:8, monitor:HDMI-A-1
workspace=name:9, monitor:HDMI-A-1
# exec-once = hyprctl dispatch workspace 1
# Good compromise for 27" or 32" 4K monitors (but fractional!)
# env = GDK_SCALE,1.75
# monitor=,preferred,auto,1.666667

# Straight 1x setup for low-resolution displays like 1080p or 1440p
# env = GDK_SCALE,1
# monitor=,preferred,auto,auto

# Example for Framework 13 w/ 6K XDR Apple display
# monitor = DP-5, 6016x3384@60, auto, 2
# monitor = :weDP-1, 2880x1920@120, auto, 2
