require("andrei.plugins-setup")
require("andrei.core.options")
require("andrei.core.keymaps")
require("andrei.core.colorscheme")
require("andrei.plugins.comment")
require("andrei.plugins.nvim-tree")
require("andrei.plugins.lualine")
require("andrei.plugins.telescope")
require("andrei.plugins.nvim-cmp")
require("andrei.plugins.lsp.ts")
require("andrei.plugins.tree-sitter")

